INFO:     Will watch for changes in these directories: ['/Users/bharath/Documents/mywork/aiagent_insta']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [77722] using StatReload
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
INFO:     Started server process [77724]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:63166 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:63166 - "GET /script.js HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:63166 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /script.js HTTP/1.1" 404 Not Found
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /script.js HTTP/1.1" 404 Not Found
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /script.js HTTP/1.1" 404 Not Found
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [77724]
INFO:     Stopping reloader process [77722]
INFO:     Will watch for changes in these directories: ['/Users/bharath/Documents/mywork/aiagent_insta']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [79816] using StatReload
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
INFO:     Started server process [79818]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /static/script.js HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
WARNING:  StatReload detected changes in 'app/utils/image_creator.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [79818]
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
INFO:     Started server process [79967]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'app/main.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [79967]
Process SpawnProcess-3:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/server.py", line 70, in serve
    await self._serve(sockets)
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/server.py", line 77, in _serve
    config.load()
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/bharath/Documents/mywork/aiagent_insta/app/main.py", line 11, in <module>
    agent = InstagramAgent()
NameError: name 'InstagramAgent' is not defined
WARNING:  StatReload detected changes in 'app/main.py'. Reloading...
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
INFO:     Started server process [80116]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [80116]
INFO:     Stopping reloader process [79816]
INFO:     Will watch for changes in these directories: ['/Users/bharath/Documents/mywork/aiagent_insta']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [80225] using StatReload
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
INFO:     Started server process [80227]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /static/script.js HTTP/1.1" 304 Not Modified
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [80227]
INFO:     Stopping reloader process [80225]
INFO:     Will watch for changes in these directories: ['/Users/bharath/Documents/mywork/aiagent_insta']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [80249] using StatReload
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
INFO:     Started server process [80251]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
WARNING:  StatReload detected changes in 'app/main.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [80251]
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
INFO:     Started server process [80310]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [80310]
INFO:     Stopping reloader process [80249]
INFO:     Will watch for changes in these directories: ['/Users/bharath/Documents/mywork/aiagent_insta']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [80335] using StatReload
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
INFO:     Started server process [80337]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
WARNING:  StatReload detected changes in 'app/utils/image_creator.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [80337]
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
INFO:     Started server process [80370]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'app/main.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [80370]
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
INFO:     Started server process [80532]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /static/script.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:63895 - "OPTIONS /post_to_instagram/ HTTP/1.1" 405 Method Not Allowed
INFO:     127.0.0.1:63897 - "POST /post_to_instagram/ HTTP/1.1" 401 Unauthorized
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [80532]
INFO:     Stopping reloader process [80335]
INFO:     Will watch for changes in these directories: ['/Users/bharath/Documents/mywork/aiagent_insta']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [80705] using StatReload
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
INFO:     Started server process [80707]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:63924 - "OPTIONS /post_to_instagram/ HTTP/1.1" 405 Method Not Allowed
INFO:     127.0.0.1:63926 - "POST /post_to_instagram/ HTTP/1.1" 401 Unauthorized
INFO:     127.0.0.1:63924 - "OPTIONS /post_to_instagram/ HTTP/1.1" 405 Method Not Allowed
INFO:     127.0.0.1:63926 - "POST /post_to_instagram/ HTTP/1.1" 401 Unauthorized
INFO:     127.0.0.1:63928 - "OPTIONS /post_to_instagram/ HTTP/1.1" 405 Method Not Allowed
INFO:     127.0.0.1:63930 - "POST /post_to_instagram/ HTTP/1.1" 401 Unauthorized
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:63935 - "OPTIONS /post_to_instagram/ HTTP/1.1" 405 Method Not Allowed
INFO:     127.0.0.1:63937 - "POST /post_to_instagram/ HTTP/1.1" 401 Unauthorized
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /static/script.js HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /static/script.js HTTP/1.1" 304 Not Modified
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /static/script.js HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /static/script.js HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /static/script.js HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /static/script.js HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /static/script.js HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "POST /post_to_instagram/ HTTP/1.1" 401 Unauthorized
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "POST /post_to_instagram/ HTTP/1.1" 401 Unauthorized
WARNING:  StatReload detected changes in 'app/main.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [80707]
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
INFO:     Started server process [80974]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [80974]
INFO:     Stopping reloader process [80705]
INFO:     Will watch for changes in these directories: ['/Users/bharath/Documents/mywork/aiagent_insta']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [80998] using StatReload
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
INFO:     Started server process [81000]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /static/script.js HTTP/1.1" 304 Not Modified
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /static/script.js HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /static/script.js HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /static/script.js HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /static/script.js HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /static/script.js HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /static/script.js HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "POST /post_to_instagram/ HTTP/1.1" 401 Unauthorized
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "POST /post_to_instagram/ HTTP/1.1" 401 Unauthorized
WARNING:  StatReload detected changes in 'app/main.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [81000]
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
INFO:     Started server process [81176]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [81176]
INFO:     Stopping reloader process [80998]
INFO:     Will watch for changes in these directories: ['/Users/bharath/Documents/mywork/aiagent_insta']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [81194] using StatReload
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
INFO:     Started server process [81196]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /static/script.js HTTP/1.1" 304 Not Modified
[INFO] Received submission with text: genarate image of lord shiva on bull
[INFO] About to generate image at: ./uploads/d549bfcf6dd648f185c8aac4e0b1972a.png
[ERROR] Failed to generate image: name 'generate_image_from_text' is not defined
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "POST /post_to_instagram/ HTTP/1.1" 200 OK
WARNING:  StatReload detected changes in 'app/main.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [81196]
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
INFO:     Started server process [81309]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'app/utils/image_creator.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [81309]
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
INFO:     Started server process [81342]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [81342]
INFO:     Stopping reloader process [81194]
INFO:     Will watch for changes in these directories: ['/Users/bharath/Documents/mywork/aiagent_insta']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [81365] using StatReload
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
INFO:     Started server process [81367]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET /static/script.js HTTP/1.1" 304 Not Modified
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "GET / HTTP/1.1" 200 OK
[INFO] Received submission with text: genarate lord ganesha eating fruits
[DEBUG] Image saved at: ./uploads/efbb8d169a964a95b5941788d025ba2b.png
[DEBUG] Image saved at: ./uploads/efbb8d169a964a95b5941788d025ba2b.png
[INFO] Image generated successfully at ./uploads/efbb8d169a964a95b5941788d025ba2b.png
[INFO] Instagram post result: Post uploaded successfully with media id: 3620697433117709547
[INFO] Temporary file cleaned up.
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "POST /post_to_instagram/ HTTP/1.1" 200 OK
[INFO] Received submission with text: genarate lord ganesha eating fruits
[DEBUG] Image saved at: ./uploads/62bd9f16e5a9462a91d8c30600832101.png
[DEBUG] Image saved at: ./uploads/62bd9f16e5a9462a91d8c30600832101.png
[INFO] Image generated successfully at ./uploads/62bd9f16e5a9462a91d8c30600832101.png
[INFO] Instagram post result: Post uploaded successfully with media id: 3620697833958929497
[INFO] Temporary file cleaned up.
INFO:     2401:4900:883a:7cfd:a813:8e1c:497f:3417:0 - "POST /post_to_instagram/ HTTP/1.1" 200 OK
WARNING:  StatReload detected changes in 'app/utils/image_creator.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [81367]
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/server.py", line 70, in serve
    await self._serve(sockets)
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/server.py", line 77, in _serve
    config.load()
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/importer.py", line 22, in import_from_string
    raise exc from None
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/bharath/Documents/mywork/aiagent_insta/app/main.py", line 6, in <module>
    from app.utils.image_creator import create_image_from_text  # ✅ Correct import for text-to-image
  File "/Users/bharath/Documents/mywork/aiagent_insta/app/utils/image_creator.py", line 1, in <module>
    from diffusers import StableDiffusionPipeline
ModuleNotFoundError: No module named 'diffusers'
WARNING:  StatReload detected changes in 'app/utils/image_creator.py'. Reloading...
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/bharath/Library/Python/3.9/lib/python/site-packages/diffusers/pipelines/pipeline_loading_utils.py:285: FutureWarning: You are loading the variant fp16 from CompVis/stable-diffusion-v1-4 via `revision='fp16'`. This behavior is deprecated and will be removed in diffusers v1. One should use `variant='fp16'` instead. However, it appears that CompVis/stable-diffusion-v1-4 currently does not have the required variant filenames in the 'main' branch. 
 The Diffusers team and community would be very grateful if you could open an issue: https://github.com/huggingface/diffusers/issues/new with the title 'CompVis/stable-diffusion-v1-4 is missing fp16 files' so that the correct variant file can be added.
  warnings.warn(
Fetching 16 files:   0%|          | 0/16 [00:00<?, ?it/s]Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Fetching 16 files:   6%|▋         | 1/16 [00:00<00:07,  1.94it/s]Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
INFO:     Will watch for changes in these directories: ['/Users/bharath/Documents/mywork/aiagent_insta']
INFO:     Uvicorn running on http://0.0.0.0:800 (Press CTRL+C to quit)
INFO:     Started reloader process [81560] using StatReload
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/bharath/Library/Python/3.9/lib/python/site-packages/diffusers/pipelines/pipeline_loading_utils.py:285: FutureWarning: You are loading the variant fp16 from CompVis/stable-diffusion-v1-4 via `revision='fp16'`. This behavior is deprecated and will be removed in diffusers v1. One should use `variant='fp16'` instead. However, it appears that CompVis/stable-diffusion-v1-4 currently does not have the required variant filenames in the 'main' branch. 
 The Diffusers team and community would be very grateful if you could open an issue: https://github.com/huggingface/diffusers/issues/new with the title 'CompVis/stable-diffusion-v1-4 is missing fp16 files' so that the correct variant file can be added.
  warnings.warn(
Fetching 16 files:   0%|          | 0/16 [00:00<?, ?it/s]Fetching 16 files:  25%|██▌       | 4/16 [02:31<08:11, 40.96s/it]Fetching 16 files:  25%|██▌       | 4/16 [01:17<03:53, 19.47s/it]Fetching 16 files:  88%|████████▊ | 14/16 [03:46<00:28, 14.35s/it]Fetching 16 files: 100%|██████████| 16/16 [03:46<00:00, 14.14s/it]
Keyword arguments {'use_auth_token': True} are not expected by StableDiffusionPipeline and will be ignored.
Loading pipeline components...:   0%|          | 0/7 [00:00<?, ?it/s]Fetching 16 files:  88%|████████▊ | 14/16 [02:32<00:20, 10.08s/it]Fetching 16 files: 100%|██████████| 16/16 [02:32<00:00,  9.53s/it]
Keyword arguments {'use_auth_token': True} are not expected by StableDiffusionPipeline and will be ignored.
Loading pipeline components...:   0%|          | 0/7 [00:00<?, ?it/s]Loading pipeline components...:  14%|█▍        | 1/7 [00:00<00:01,  5.89it/s]Loading pipeline components...:  14%|█▍        | 1/7 [00:00<00:01,  4.71it/s]An error occurred while trying to fetch /Users/bharath/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/unet: Error no file named diffusion_pytorch_model.safetensors found in directory /Users/bharath/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/unet.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
/Users/bharath/Library/Python/3.9/lib/python/site-packages/transformers/models/clip/feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
Loading pipeline components...:  43%|████▎     | 3/7 [00:00<00:00,  5.38it/s]An error occurred while trying to fetch /Users/bharath/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/unet: Error no file named diffusion_pytorch_model.safetensors found in directory /Users/bharath/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/unet.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
Loading pipeline components...:  43%|████▎     | 3/7 [00:00<00:00,  5.63it/s]Loading pipeline components...:  71%|███████▏  | 5/7 [00:00<00:00,  8.61it/s]An error occurred while trying to fetch /Users/bharath/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/vae: Error no file named diffusion_pytorch_model.safetensors found in directory /Users/bharath/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/vae.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
Loading pipeline components...: 100%|██████████| 7/7 [00:00<00:00, 11.04it/s]Loading pipeline components...: 100%|██████████| 7/7 [00:00<00:00,  9.00it/s]
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
INFO:     Started server process [81534]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
Loading pipeline components...:  71%|███████▏  | 5/7 [00:00<00:00,  6.76it/s]ERROR:    Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/server.py", line 70, in serve
    await self._serve(sockets)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/server.py", line 330, in capture_signals
    signal.raise_signal(captured_signal)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/starlette/routing.py", line 699, in lifespan
    await receive()
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/queues.py", line 166, in get
    await getter
asyncio.exceptions.CancelledError

/Users/bharath/Library/Python/3.9/lib/python/site-packages/transformers/models/clip/feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
An error occurred while trying to fetch /Users/bharath/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/vae: Error no file named diffusion_pytorch_model.safetensors found in directory /Users/bharath/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/vae.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
Loading pipeline components...: 100%|██████████| 7/7 [00:00<00:00,  8.47it/s]
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
INFO:     Started server process [81562]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/server.py", line 70, in serve
    await self._serve(sockets)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/server.py", line 330, in capture_signals
    signal.raise_signal(captured_signal)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/starlette/routing.py", line 699, in lifespan
    await receive()
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/queues.py", line 166, in get
    await getter
asyncio.exceptions.CancelledError

INFO:     Stopping reloader process [81560]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 333, in _bootstrap
    threading._shutdown()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 1448, in _shutdown
    lock.acquire()
KeyboardInterrupt
INFO:     Stopping reloader process [81365]
INFO:     Will watch for changes in these directories: ['/Users/bharath/Documents/mywork/aiagent_insta']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [83840] using StatReload
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/bharath/Library/Python/3.9/lib/python/site-packages/diffusers/pipelines/pipeline_loading_utils.py:285: FutureWarning: You are loading the variant fp16 from CompVis/stable-diffusion-v1-4 via `revision='fp16'`. This behavior is deprecated and will be removed in diffusers v1. One should use `variant='fp16'` instead. However, it appears that CompVis/stable-diffusion-v1-4 currently does not have the required variant filenames in the 'main' branch. 
 The Diffusers team and community would be very grateful if you could open an issue: https://github.com/huggingface/diffusers/issues/new with the title 'CompVis/stable-diffusion-v1-4 is missing fp16 files' so that the correct variant file can be added.
  warnings.warn(
Keyword arguments {'use_auth_token': True} are not expected by StableDiffusionPipeline and will be ignored.
Loading pipeline components...:   0%|          | 0/7 [00:00<?, ?it/s]An error occurred while trying to fetch /Users/bharath/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/vae: Error no file named diffusion_pytorch_model.safetensors found in directory /Users/bharath/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/vae.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
/Users/bharath/Library/Python/3.9/lib/python/site-packages/transformers/models/clip/feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
Loading pipeline components...:  57%|█████▋    | 4/7 [00:00<00:00, 39.30it/s]An error occurred while trying to fetch /Users/bharath/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/unet: Error no file named diffusion_pytorch_model.safetensors found in directory /Users/bharath/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/unet.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
Loading pipeline components...: 100%|██████████| 7/7 [00:00<00:00, 10.36it/s]
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
INFO:     Started server process [83842]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     2401:4900:883a:a265:f129:23ba:7b9f:d467:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:a265:f129:23ba:7b9f:d467:0 - "GET /static/script.js HTTP/1.1" 304 Not Modified
[INFO] Received submission with text: genarate lord ganesha image eating fruits
[ERROR] Unhandled exception: name 'prompt' is not defined
INFO:     2401:4900:883a:a265:f129:23ba:7b9f:d467:0 - "POST /post_to_instagram/ HTTP/1.1" 200 OK
WARNING:  StatReload detected changes in 'app/main.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [83842]
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/bharath/Library/Python/3.9/lib/python/site-packages/diffusers/pipelines/pipeline_loading_utils.py:285: FutureWarning: You are loading the variant fp16 from CompVis/stable-diffusion-v1-4 via `revision='fp16'`. This behavior is deprecated and will be removed in diffusers v1. One should use `variant='fp16'` instead. However, it appears that CompVis/stable-diffusion-v1-4 currently does not have the required variant filenames in the 'main' branch. 
 The Diffusers team and community would be very grateful if you could open an issue: https://github.com/huggingface/diffusers/issues/new with the title 'CompVis/stable-diffusion-v1-4 is missing fp16 files' so that the correct variant file can be added.
  warnings.warn(
Keyword arguments {'use_auth_token': True} are not expected by StableDiffusionPipeline and will be ignored.
Loading pipeline components...:   0%|          | 0/7 [00:00<?, ?it/s]Loading pipeline components...:  14%|█▍        | 1/7 [00:00<00:00,  7.21it/s]Loading pipeline components...:  43%|████▎     | 3/7 [00:00<00:00,  6.03it/s]An error occurred while trying to fetch /Users/bharath/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/unet: Error no file named diffusion_pytorch_model.safetensors found in directory /Users/bharath/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/unet.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
Loading pipeline components...:  57%|█████▋    | 4/7 [00:00<00:00,  6.52it/s]An error occurred while trying to fetch /Users/bharath/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/vae: Error no file named diffusion_pytorch_model.safetensors found in directory /Users/bharath/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/vae.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
/Users/bharath/Library/Python/3.9/lib/python/site-packages/transformers/models/clip/feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
Loading pipeline components...: 100%|██████████| 7/7 [00:00<00:00,  9.87it/s]
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
INFO:     Started server process [83880]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [83880]
INFO:     Stopping reloader process [83840]
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
INFO:     Will watch for changes in these directories: ['/Users/bharath/Documents/mywork/aiagent_insta']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [83935] using StatReload
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/bharath/Library/Python/3.9/lib/python/site-packages/diffusers/pipelines/pipeline_loading_utils.py:285: FutureWarning: You are loading the variant fp16 from CompVis/stable-diffusion-v1-4 via `revision='fp16'`. This behavior is deprecated and will be removed in diffusers v1. One should use `variant='fp16'` instead. However, it appears that CompVis/stable-diffusion-v1-4 currently does not have the required variant filenames in the 'main' branch. 
 The Diffusers team and community would be very grateful if you could open an issue: https://github.com/huggingface/diffusers/issues/new with the title 'CompVis/stable-diffusion-v1-4 is missing fp16 files' so that the correct variant file can be added.
  warnings.warn(
Keyword arguments {'use_auth_token': True} are not expected by StableDiffusionPipeline and will be ignored.
Loading pipeline components...:   0%|          | 0/7 [00:00<?, ?it/s]An error occurred while trying to fetch /Users/bharath/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/unet: Error no file named diffusion_pytorch_model.safetensors found in directory /Users/bharath/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/unet.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
Loading pipeline components...:  14%|█▍        | 1/7 [00:00<00:00,  7.44it/s]Loading pipeline components...:  29%|██▊       | 2/7 [00:00<00:01,  4.28it/s]Loading pipeline components...:  43%|████▎     | 3/7 [00:00<00:00,  5.26it/s]/Users/bharath/Library/Python/3.9/lib/python/site-packages/transformers/models/clip/feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
An error occurred while trying to fetch /Users/bharath/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/vae: Error no file named diffusion_pytorch_model.safetensors found in directory /Users/bharath/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/vae.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
Loading pipeline components...: 100%|██████████| 7/7 [00:00<00:00, 14.11it/s]Loading pipeline components...: 100%|██████████| 7/7 [00:00<00:00, 10.35it/s]
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
INFO:     Started server process [83937]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
[INFO] Received submission with text: genarate lord ganesha image eating fruits
[DEBUG] Generating AI image for prompt: genarate lord ganesha image eating fruits
  0%|          | 0/50 [00:00<?, ?it/s]INFO:     Will watch for changes in these directories: ['/Users/bharath/Documents/mywork/aiagent_insta']
ERROR:    [Errno 48] Address already in use
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
INFO:     Will watch for changes in these directories: ['/Users/bharath/Documents/mywork/aiagent_insta']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [84115] using StatReload
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/bharath/Library/Python/3.9/lib/python/site-packages/diffusers/pipelines/pipeline_loading_utils.py:285: FutureWarning: You are loading the variant fp16 from CompVis/stable-diffusion-v1-4 via `revision='fp16'`. This behavior is deprecated and will be removed in diffusers v1. One should use `variant='fp16'` instead. However, it appears that CompVis/stable-diffusion-v1-4 currently does not have the required variant filenames in the 'main' branch. 
 The Diffusers team and community would be very grateful if you could open an issue: https://github.com/huggingface/diffusers/issues/new with the title 'CompVis/stable-diffusion-v1-4 is missing fp16 files' so that the correct variant file can be added.
  warnings.warn(
Keyword arguments {'use_auth_token': True} are not expected by StableDiffusionPipeline and will be ignored.
Loading pipeline components...:   0%|          | 0/7 [00:00<?, ?it/s]/Users/bharath/Library/Python/3.9/lib/python/site-packages/transformers/models/clip/feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
Loading pipeline components...:  29%|██▊       | 2/7 [00:00<00:00, 12.67it/s]An error occurred while trying to fetch /Users/bharath/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/vae: Error no file named diffusion_pytorch_model.safetensors found in directory /Users/bharath/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/vae.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
An error occurred while trying to fetch /Users/bharath/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/unet: Error no file named diffusion_pytorch_model.safetensors found in directory /Users/bharath/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/unet.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
Loading pipeline components...:  57%|█████▋    | 4/7 [00:00<00:00, 11.41it/s]Loading pipeline components...:  86%|████████▌ | 6/7 [00:00<00:00,  7.70it/s]Loading pipeline components...: 100%|██████████| 7/7 [00:00<00:00,  9.79it/s]
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
INFO:     Started server process [84117]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     2401:4900:883a:a265:f129:23ba:7b9f:d467:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:a265:f129:23ba:7b9f:d467:0 - "GET /favicon.ico HTTP/1.1" 404 Not Found
[INFO] Received submission with text: genarate lord ganesh image in the forest
[DEBUG] Generating AI image for prompt: genarate lord ganesh image in the forest
  0%|          | 0/50 [00:00<?, ?it/s]WARNING:  StatReload detected changes in 'app/utils/image_creator.py'. Reloading...
  2%|▏         | 1/50 [47:48<39:02:53, 2868.85s/it]INFO:     Will watch for changes in these directories: ['/Users/bharath/Documents/mywork/aiagent_insta']
ERROR:    [Errno 48] Address already in use
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
INFO:     Will watch for changes in these directories: ['/Users/bharath/Documents/mywork/aiagent_insta']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [84915] using StatReload
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Loading pipeline components...:   0%|          | 0/7 [00:00<?, ?it/s]Loading pipeline components...:  43%|████▎     | 3/7 [00:00<00:00, 23.21it/s]Loading pipeline components...:  86%|████████▌ | 6/7 [00:00<00:00, 20.66it/s]Loading pipeline components...: 100%|██████████| 7/7 [00:00<00:00, 21.77it/s]
INFO:     Started server process [84917]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     2401:4900:883a:a265:f129:23ba:7b9f:d467:0 - "GET / HTTP/1.1" 200 OK
[INFO] Received submission with text: fish in water
[DEBUG] Generating AI image for prompt: fish in water
  0%|          | 0/20 [00:00<?, ?it/s]  5%|▌         | 1/20 [00:29<09:20, 29.50s/it] 10%|█         | 2/20 [00:44<06:13, 20.74s/it] 15%|█▌        | 3/20 [00:58<04:59, 17.63s/it] 20%|██        | 4/20 [01:11<04:17, 16.12s/it] 25%|██▌       | 5/20 [01:25<03:50, 15.38s/it] 30%|███       | 6/20 [01:40<03:30, 15.03s/it] 35%|███▌      | 7/20 [01:54<03:10, 14.65s/it] 40%|████      | 8/20 [02:08<02:53, 14.47s/it] 45%|████▌     | 9/20 [02:22<02:37, 14.28s/it] 50%|█████     | 10/20 [02:35<02:20, 14.09s/it] 55%|█████▌    | 11/20 [02:49<02:06, 14.05s/it] 60%|██████    | 12/20 [03:03<01:51, 13.95s/it] 65%|██████▌   | 13/20 [03:17<01:37, 13.92s/it] 70%|███████   | 14/20 [03:33<01:27, 14.59s/it] 75%|███████▌  | 15/20 [03:47<01:12, 14.43s/it] 80%|████████  | 16/20 [04:01<00:57, 14.41s/it] 85%|████████▌ | 17/20 [04:15<00:42, 14.26s/it] 90%|█████████ | 18/20 [04:29<00:28, 14.22s/it] 95%|█████████▌| 19/20 [04:44<00:14, 14.24s/it]100%|██████████| 20/20 [04:59<00:00, 14.52s/it]100%|██████████| 20/20 [04:59<00:00, 14.97s/it]
[DEBUG] Image saved at: ./uploads/c2f6d2d39de94b008689e0df98976ccc.png
[DEBUG] Generating AI image for prompt: fish in water
  0%|          | 0/20 [00:00<?, ?it/s]  5%|▌         | 1/20 [00:29<09:17, 29.33s/it] 10%|█         | 2/20 [00:42<06:01, 20.07s/it] 15%|█▌        | 3/20 [00:58<05:03, 17.84s/it] 20%|██        | 4/20 [01:12<04:22, 16.38s/it] 25%|██▌       | 5/20 [01:26<03:52, 15.51s/it] 30%|███       | 6/20 [01:40<03:29, 14.95s/it] 35%|███▌      | 7/20 [01:53<03:09, 14.59s/it] 40%|████      | 8/20 [02:07<02:52, 14.37s/it] 45%|████▌     | 9/20 [02:21<02:37, 14.28s/it] 50%|█████     | 10/20 [02:35<02:21, 14.14s/it] 55%|█████▌    | 11/20 [02:49<02:06, 14.05s/it] 60%|██████    | 12/20 [03:03<01:52, 14.04s/it] 65%|██████▌   | 13/20 [03:17<01:38, 14.12s/it] 70%|███████   | 14/20 [03:32<01:25, 14.23s/it] 75%|███████▌  | 15/20 [03:46<01:11, 14.26s/it] 80%|████████  | 16/20 [04:00<00:56, 14.19s/it] 85%|████████▌ | 17/20 [04:15<00:42, 14.24s/it] 90%|█████████ | 18/20 [04:29<00:28, 14.23s/it] 95%|█████████▌| 19/20 [04:43<00:14, 14.33s/it]100%|██████████| 20/20 [04:59<00:00, 14.73s/it]100%|██████████| 20/20 [04:59<00:00, 14.98s/it]
[DEBUG] Image saved at: ./uploads/c2f6d2d39de94b008689e0df98976ccc.png
[INFO] Image generated successfully at ./uploads/c2f6d2d39de94b008689e0df98976ccc.png
[INFO] Instagram post result: Post uploaded successfully with media id: 3621262818862838094
[INFO] Temporary file cleaned up.
INFO:     2401:4900:883a:a265:f129:23ba:7b9f:d467:0 - "POST /post_to_instagram/ HTTP/1.1" 200 OK
[INFO] Received submission with text: fish in water
[DEBUG] Generating AI image for prompt: fish in water
  0%|          | 0/20 [00:00<?, ?it/s]  5%|▌         | 1/20 [00:26<08:30, 26.89s/it] 10%|█         | 2/20 [00:40<05:43, 19.06s/it] 15%|█▌        | 3/20 [00:54<04:42, 16.61s/it] 20%|██        | 4/20 [01:07<04:06, 15.41s/it] 25%|██▌       | 5/20 [01:21<03:41, 14.79s/it] 30%|███       | 6/20 [01:35<03:21, 14.39s/it] 35%|███▌      | 7/20 [01:48<03:03, 14.15s/it] 40%|████      | 8/20 [02:03<02:50, 14.21s/it] 45%|████▌     | 9/20 [06:25<16:51, 91.93s/it] 50%|█████     | 10/20 [06:39<11:17, 67.77s/it] 55%|█████▌    | 11/20 [06:53<07:41, 51.26s/it] 60%|██████    | 12/20 [07:06<05:18, 39.77s/it] 65%|██████▌   | 13/20 [07:20<03:42, 31.86s/it] 70%|███████   | 14/20 [07:34<02:38, 26.37s/it] 75%|███████▌  | 15/20 [07:47<01:52, 22.56s/it] 80%|████████  | 16/20 [08:01<01:19, 19.93s/it] 85%|████████▌ | 17/20 [08:16<00:54, 18.25s/it] 90%|█████████ | 18/20 [08:29<00:33, 16.86s/it] 95%|█████████▌| 19/20 [08:43<00:16, 16.01s/it]100%|██████████| 20/20 [08:58<00:00, 15.50s/it]100%|██████████| 20/20 [08:58<00:00, 26.90s/it]
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
INFO:     Will watch for changes in these directories: ['/Users/bharath/Documents/mywork/aiagent_insta']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [85409] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/server.py", line 70, in serve
    await self._serve(sockets)
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/server.py", line 77, in _serve
    config.load()
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/bharath/Library/Python/3.9/lib/python/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/bharath/Documents/mywork/aiagent_insta/app/main.py", line 26
    print(f"[ERROR] Failed to post to Instagram: {insta_error}")
IndentationError: unexpected indent
INFO:     Will watch for changes in these directories: ['/Users/bharath/Documents/mywork/aiagent_insta']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [85512] using StatReload
/Users/bharath/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Loading pipeline components...:   0%|          | 0/7 [00:00<?, ?it/s]Loading pipeline components...:  14%|█▍        | 1/7 [00:00<00:00,  8.90it/s]Loading pipeline components...:  29%|██▊       | 2/7 [00:00<00:00,  8.43it/s]Loading pipeline components...: 100%|██████████| 7/7 [00:00<00:00, 24.24it/s]Loading pipeline components...: 100%|██████████| 7/7 [00:00<00:00, 20.02it/s]
INFO:     Started server process [85514]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     2401:4900:883a:a265:f129:23ba:7b9f:d467:0 - "GET / HTTP/1.1" 200 OK
[INFO] Received submission with text: genarate image fish in the pond
[INFO] About to generate image at: ./uploads/7bc5aef21f01489889d195c61c608153.png
[DEBUG] Generating AI image for prompt: genarate image fish in the pond
  0%|          | 0/20 [00:00<?, ?it/s]  5%|▌         | 1/20 [00:27<08:45, 27.64s/it] 10%|█         | 2/20 [00:41<05:52, 19.57s/it] 15%|█▌        | 3/20 [00:55<04:48, 16.94s/it] 20%|██        | 4/20 [01:09<04:12, 15.77s/it] 25%|██▌       | 5/20 [01:23<03:46, 15.07s/it] 30%|███       | 6/20 [01:37<03:29, 14.95s/it] 35%|███▌      | 7/20 [01:51<03:09, 14.57s/it] 40%|████      | 8/20 [02:05<02:52, 14.38s/it] 45%|████▌     | 9/20 [02:19<02:35, 14.16s/it] 50%|█████     | 10/20 [02:33<02:20, 14.05s/it] 55%|█████▌    | 11/20 [02:47<02:06, 14.01s/it] 60%|██████    | 12/20 [03:00<01:51, 13.95s/it] 65%|██████▌   | 13/20 [03:14<01:37, 13.91s/it] 70%|███████   | 14/20 [03:28<01:23, 13.99s/it] 75%|███████▌  | 15/20 [03:42<01:09, 13.95s/it] 80%|████████  | 16/20 [03:56<00:55, 13.94s/it] 85%|████████▌ | 17/20 [04:11<00:42, 14.14s/it] 90%|█████████ | 18/20 [04:32<00:32, 16.41s/it] 95%|█████████▌| 19/20 [04:47<00:15, 15.85s/it]100%|██████████| 20/20 [05:01<00:00, 15.18s/it]100%|██████████| 20/20 [05:01<00:00, 15.06s/it]
[DEBUG] Image saved at: ./uploads/7bc5aef21f01489889d195c61c608153.png
[INFO] Image generated successfully.
[INFO] Instagram post result: Post uploaded successfully with media id: 3621274205735609046
[INFO] Temporary file removed.
INFO:     2401:4900:883a:a265:f129:23ba:7b9f:d467:0 - "POST /post_to_instagram/ HTTP/1.1" 200 OK
INFO:     2401:4900:883a:a265:58ee:d127:cff:be0a:0 - "GET / HTTP/1.1" 206 Partial Content
INFO:     2401:4900:883a:a265:58ee:d127:cff:be0a:0 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     2401:4900:883a:a265:58ee:d127:cff:be0a:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:a265:58ee:d127:cff:be0a:0 - "GET /static/script.js HTTP/1.1" 200 OK
INFO:     2401:4900:91eb:f00e:8c44:11d7:b5da:3cb9:0 - "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 Not Found
INFO:     2401:4900:91eb:f00e:8c44:11d7:b5da:3cb9:0 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     2401:4900:91eb:f00e:8c44:11d7:b5da:3cb9:0 - "GET /apple-touch-icon.png HTTP/1.1" 404 Not Found
INFO:     2401:4900:91eb:f00e:8c44:11d7:b5da:3cb9:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:91eb:f00e:8c44:11d7:b5da:3cb9:0 - "GET /static/script.js HTTP/1.1" 200 OK
INFO:     2409:40f2:1161:5fa2:2409:9514:8282:df1c:0 - "GET / HTTP/1.1" 200 OK
INFO:     2409:40f2:1161:5fa2:2409:9514:8282:df1c:0 - "GET /static/script.js HTTP/1.1" 200 OK
[INFO] Received submission with text: Generate an image of a futuristic rose flower in an balcony of the tower hanging from asteroid to earth.
[INFO] About to generate image at: ./uploads/8a0f95ba5d354224ab469f33031f7bb6.png
[DEBUG] Generating AI image for prompt: Generate an image of a futuristic rose flower in an balcony of the tower hanging from asteroid to earth.
  0%|          | 0/20 [00:00<?, ?it/s]  5%|▌         | 1/20 [00:28<09:00, 28.43s/it] 10%|█         | 2/20 [00:42<05:57, 19.87s/it] 15%|█▌        | 3/20 [00:56<04:55, 17.40s/it] 20%|██        | 4/20 [01:13<04:32, 17.02s/it] 25%|██▌       | 5/20 [01:28<04:04, 16.33s/it] 30%|███       | 6/20 [01:45<03:51, 16.54s/it] 35%|███▌      | 7/20 [02:00<03:29, 16.11s/it] 40%|████      | 8/20 [02:15<03:09, 15.77s/it] 45%|████▌     | 9/20 [02:29<02:47, 15.26s/it] 50%|█████     | 10/20 [02:44<02:30, 15.07s/it] 55%|█████▌    | 11/20 [02:58<02:13, 14.82s/it] 60%|██████    | 12/20 [03:12<01:56, 14.53s/it] 65%|██████▌   | 13/20 [03:26<01:40, 14.38s/it] 70%|███████   | 14/20 [03:40<01:25, 14.26s/it] 75%|███████▌  | 15/20 [03:54<01:10, 14.17s/it] 80%|████████  | 16/20 [04:08<00:56, 14.13s/it] 85%|████████▌ | 17/20 [04:22<00:42, 14.04s/it] 90%|█████████ | 18/20 [04:36<00:28, 14.12s/it] 95%|█████████▌| 19/20 [04:50<00:14, 14.12s/it]100%|██████████| 20/20 [05:05<00:00, 14.20s/it]100%|██████████| 20/20 [05:05<00:00, 15.25s/it]
[DEBUG] Image saved at: ./uploads/8a0f95ba5d354224ab469f33031f7bb6.png
[INFO] Image generated successfully.
[ERROR] Unhandled exception: You can log in with your linked Facebook account. If you are sure that the password is correct, then change your IP address, because it is added to the blacklist of the Instagram Server
INFO:     2409:40f2:1161:5fa2:2409:9514:8282:df1c:0 - "POST /post_to_instagram/ HTTP/1.1" 200 OK
INFO:     2409:40f2:1161:5fa2:2409:9514:8282:df1c:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:a265:f129:23ba:7b9f:d467:0 - "GET / HTTP/1.1" 200 OK
INFO:     2401:4900:883a:a265:f129:23ba:7b9f:d467:0 - "GET /static/script.js HTTP/1.1" 304 Not Modified
[INFO] Received submission with text: genarate a bird flying above the ocean
[INFO] About to generate image at: ./uploads/3d2291e8e5d14fedaf9201ce48249347.png
[DEBUG] Generating AI image for prompt: genarate a bird flying above the ocean
  0%|          | 0/20 [00:00<?, ?it/s]  5%|▌         | 1/20 [00:30<09:33, 30.16s/it] 10%|█         | 2/20 [00:44<06:15, 20.88s/it] 15%|█▌        | 3/20 [00:59<05:06, 18.06s/it] 20%|██        | 4/20 [01:14<04:29, 16.87s/it] 25%|██▌       | 5/20 [01:28<04:00, 16.01s/it] 30%|███       | 6/20 [01:43<03:37, 15.52s/it] 35%|███▌      | 7/20 [01:57<03:16, 15.14s/it] 40%|████      | 8/20 [02:11<02:58, 14.87s/it] 45%|████▌     | 9/20 [02:26<02:42, 14.73s/it] 50%|█████     | 10/20 [02:41<02:27, 14.71s/it] 55%|█████▌    | 11/20 [02:55<02:11, 14.62s/it] 60%|██████    | 12/20 [03:09<01:56, 14.56s/it] 65%|██████▌   | 13/20 [03:24<01:41, 14.50s/it] 70%|███████   | 14/20 [03:38<01:27, 14.53s/it] 75%|███████▌  | 15/20 [03:53<01:12, 14.43s/it] 80%|████████  | 16/20 [04:07<00:57, 14.45s/it] 85%|████████▌ | 17/20 [04:21<00:43, 14.43s/it] 90%|█████████ | 18/20 [04:36<00:28, 14.41s/it] 95%|█████████▌| 19/20 [04:50<00:14, 14.41s/it]100%|██████████| 20/20 [05:05<00:00, 14.39s/it]100%|██████████| 20/20 [05:05<00:00, 15.25s/it]
[DEBUG] Image saved at: ./uploads/3d2291e8e5d14fedaf9201ce48249347.png
[INFO] Image generated successfully.
[INFO] Instagram post result: Post uploaded successfully with media id: 3621307323641028904
[INFO] Temporary file removed.
INFO:     2401:4900:883a:a265:f129:23ba:7b9f:d467:0 - "POST /post_to_instagram/ HTTP/1.1" 200 OK
[INFO] Received submission with text: Generate a image of spaceship docked in my balcony of my future home while i chat with my home robot
[INFO] About to generate image at: ./uploads/9bf7eae03b354cfc81a5070d0e341700.png
[DEBUG] Generating AI image for prompt: Generate a image of spaceship docked in my balcony of my future home while i chat with my home robot
  0%|          | 0/20 [00:00<?, ?it/s]  5%|▌         | 1/20 [00:30<09:34, 30.23s/it] 10%|█         | 2/20 [00:45<06:28, 21.59s/it] 15%|█▌        | 3/20 [01:00<05:11, 18.34s/it] 20%|██        | 4/20 [01:14<04:30, 16.91s/it] 25%|██▌       | 5/20 [01:29<04:00, 16.05s/it] 30%|███       | 6/20 [01:44<03:41, 15.83s/it] 35%|███▌      | 7/20 [02:00<03:23, 15.63s/it] 40%|████      | 8/20 [02:15<03:06, 15.55s/it] 45%|████▌     | 9/20 [02:30<02:48, 15.34s/it] 50%|█████     | 10/20 [02:46<02:35, 15.54s/it] 55%|█████▌    | 11/20 [03:02<02:22, 15.79s/it] 60%|██████    | 12/20 [03:18<02:07, 15.91s/it] 65%|██████▌   | 13/20 [03:35<01:53, 16.16s/it] 70%|███████   | 14/20 [03:51<01:37, 16.18s/it] 75%|███████▌  | 15/20 [04:08<01:21, 16.35s/it] 80%|████████  | 16/20 [04:24<01:04, 16.18s/it] 85%|████████▌ | 17/20 [04:40<00:48, 16.10s/it] 90%|█████████ | 18/20 [04:56<00:32, 16.04s/it] 95%|█████████▌| 19/20 [05:11<00:15, 15.95s/it]100%|██████████| 20/20 [05:28<00:00, 16.17s/it]100%|██████████| 20/20 [05:28<00:00, 16.43s/it]
[DEBUG] Image saved at: ./uploads/9bf7eae03b354cfc81a5070d0e341700.png
[INFO] Image generated successfully.
[ERROR] Unhandled exception: You can log in with your linked Facebook account. If you are sure that the password is correct, then change your IP address, because it is added to the blacklist of the Instagram Server
INFO:     2409:40f2:1161:5fa2:2409:9514:8282:df1c:0 - "POST /post_to_instagram/ HTTP/1.1" 200 OK
[INFO] Received submission with text: Generate a image of spaceship docked in my balcony of my future home while i chat with my home robot
[INFO] About to generate image at: ./uploads/646859a98551413d8a9cad6caa45a349.png
[DEBUG] Generating AI image for prompt: Generate a image of spaceship docked in my balcony of my future home while i chat with my home robot
  0%|          | 0/20 [00:00<?, ?it/s]  5%|▌         | 1/20 [00:27<08:46, 27.71s/it] 10%|█         | 2/20 [01:10<10:57, 36.51s/it] 15%|█▌        | 3/20 [01:26<07:38, 26.98s/it] 20%|██        | 4/20 [01:40<05:50, 21.89s/it] 25%|██▌       | 5/20 [18:07<1:32:31, 370.10s/it] 30%|███       | 6/20 [18:22<58:09, 249.27s/it]   35%|███▌      | 7/20 [18:36<37:21, 172.41s/it] 40%|████      | 8/20 [18:50<24:24, 122.07s/it] 45%|████▌     | 9/20 [19:05<16:12, 88.40s/it]  50%|█████     | 10/20 [35:12<59:57, 359.75s/it] 55%|█████▌    | 11/20 [35:26<38:05, 253.97s/it] 60%|██████    | 12/20 [35:41<24:08, 181.12s/it] 65%|██████▌   | 13/20 [50:56<47:04, 403.47s/it] 70%|███████   | 14/20 [51:12<28:38, 286.50s/it] 75%|███████▌  | 15/20 [51:26<17:02, 204.47s/it] 80%|████████  | 16/20 [51:41<09:49, 147.34s/it] 85%|████████▌ | 17/20 [1:08:06<19:57, 399.20s/it] 90%|█████████ | 18/20 [1:08:21<09:27, 283.67s/it] 95%|█████████▌| 19/20 [1:08:35<03:22, 202.89s/it]100%|██████████| 20/20 [1:10:25<00:00, 175.05s/it]100%|██████████| 20/20 [1:10:25<00:00, 211.30s/it]
[DEBUG] Image saved at: ./uploads/646859a98551413d8a9cad6caa45a349.png
[INFO] Image generated successfully.
[ERROR] Unhandled exception: You can log in with your linked Facebook account. If you are sure that the password is correct, then change your IP address, because it is added to the blacklist of the Instagram Server
INFO:      - "POST /post_to_instagram/ HTTP/1.1" 200 OK
[INFO] Received submission with text: Generate a image of spaceship docked in my balcony of my future home while i chat with my home robot
[INFO] About to generate image at: ./uploads/3621c856337940f8b712d7d899829bc3.png
[DEBUG] Generating AI image for prompt: Generate a image of spaceship docked in my balcony of my future home while i chat with my home robot
  0%|          | 0/20 [00:00<?, ?it/s]  5%|▌         | 1/20 [00:47<15:03, 47.55s/it] 10%|█         | 2/20 [01:01<08:24, 28.01s/it] 15%|█▌        | 3/20 [01:15<06:07, 21.63s/it] 20%|██        | 4/20 [01:31<05:08, 19.28s/it] 25%|██▌       | 5/20 [01:46<04:26, 17.73s/it] 30%|███       | 6/20 [02:01<03:53, 16.71s/it] 35%|███▌      | 7/20 [02:16<03:32, 16.35s/it] 40%|████      | 8/20 [02:31<03:10, 15.85s/it] 45%|████▌     | 9/20 [02:46<02:51, 15.62s/it] 50%|█████     | 10/20 [03:01<02:34, 15.42s/it] 55%|█████▌    | 11/20 [03:16<02:17, 15.31s/it] 60%|██████    | 12/20 [03:31<02:01, 15.20s/it] 65%|██████▌   | 13/20 [03:47<01:47, 15.30s/it] 70%|███████   | 14/20 [04:02<01:31, 15.19s/it] 75%|███████▌  | 15/20 [04:17<01:15, 15.16s/it] 80%|████████  | 16/20 [04:32<01:00, 15.20s/it] 85%|████████▌ | 17/20 [04:47<00:45, 15.20s/it] 90%|█████████ | 18/20 [09:15<03:02, 91.01s/it] 95%|█████████▌| 19/20 [09:29<01:07, 67.99s/it]100%|██████████| 20/20 [09:44<00:00, 51.91s/it]100%|██████████| 20/20 [09:44<00:00, 29.21s/it]
[DEBUG] Image saved at: ./uploads/3621c856337940f8b712d7d899829bc3.png
[INFO] Image generated successfully.
[ERROR] Unhandled exception: You can log in with your linked Facebook account. If you are sure that the password is correct, then change your IP address, because it is added to the blacklist of the Instagram Server
INFO:      - "POST /post_to_instagram/ HTTP/1.1" 200 OK
[INFO] Received submission with text: Generate a image of spaceship docked in my balcony of my future home while i chat with my home robot
[INFO] About to generate image at: ./uploads/b69f51a9d49448d2aa049917fcb576c4.png
[DEBUG] Generating AI image for prompt: Generate a image of spaceship docked in my balcony of my future home while i chat with my home robot
  0%|          | 0/20 [00:00<?, ?it/s]  5%|▌         | 1/20 [00:29<09:13, 29.12s/it] 10%|█         | 2/20 [00:43<06:04, 20.23s/it] 15%|█▌        | 3/20 [00:57<04:57, 17.51s/it] 20%|██        | 4/20 [01:11<04:20, 16.30s/it] 25%|██▌       | 5/20 [01:25<03:52, 15.50s/it] 30%|███       | 6/20 [01:40<03:31, 15.13s/it] 35%|███▌      | 7/20 [01:54<03:12, 14.77s/it] 40%|████      | 8/20 [02:27<04:09, 20.76s/it] 45%|████▌     | 9/20 [02:53<04:05, 22.28s/it] 50%|█████     | 10/20 [03:48<05:22, 32.27s/it] 55%|█████▌    | 11/20 [04:02<04:01, 26.82s/it] 60%|██████    | 12/20 [11:23<20:22, 152.84s/it] 65%|██████▌   | 13/20 [11:38<12:56, 110.87s/it] 70%|███████   | 14/20 [11:53<08:11, 81.94s/it]  75%|███████▌  | 15/20 [13:39<07:26, 89.26s/it] 80%|████████  | 16/20 [13:54<04:27, 66.87s/it] 85%|████████▌ | 17/20 [14:08<02:33, 51.18s/it] 90%|█████████ | 18/20 [15:25<01:57, 58.71s/it] 95%|█████████▌| 19/20 [15:40<00:45, 45.74s/it]100%|██████████| 20/20 [15:55<00:00, 36.37s/it]100%|██████████| 20/20 [15:55<00:00, 47.76s/it]
[DEBUG] Image saved at: ./uploads/b69f51a9d49448d2aa049917fcb576c4.png
[INFO] Image generated successfully.
Enter code (6 digits) for duvvurulokesh (ChallengeChoice.EMAIL): 